class GameSettings:
    SCREEN_WIDTH = 800
    SCREEN_HEIGHT = 600
    GAME_WORLD_WIDTH = int(SCREEN_WIDTH * 0.75)
    GAME_WORLD_HEIGHT = SCREEN_HEIGHT
    UI_AREA_WIDTH = int(SCREEN_WIDTH * 0.25)
    UI_AREA_HEIGHT = SCREEN_HEIGHT
    MENU_STATE = "menu"


