[tool.poetry]
name = "chatgpt-game"
version = "0.1.0"
description = ""
authors = ["CryptoRalph <doxter@protonmail.com>"]
readme = "README.md"
packages = [{include = "chatgpt_game"}]

[tool.poetry.dependencies]
python = "^3.11"
pygame = "^2.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
